server:
  port: 8082
  servlet:
    contextPath: /chesscorner

spring:
    datasource:
      password: intruderZ5813
      url: jdbc:mysql://localhost:3306/IG308_chess_web_shop?user=root
      driverClassName: com.mysql.cj.jdbc.Driver

#    jpa:
#      show_sql: true
#      properties:
#        hibernate:
#          format_sql: true

